#!/usr/bin/env bash

cd $(dirname $0)

_backup () {
    local the_original
    local the_backup
    the_original=$1
    the_backup=$1.BACKUP
    [ -L ${the_original} ] && rm ${the_original} 
    [ -e ${the_original} ] || return
    echo "  move: [${the_original}] -> [${the_backup}]"
    mv ${the_original} ${the_backup}
}

_link () {
    real=$1
    name=$(basename $1)
    [ ! ${name:0:1} == . ] && name=.${name}
    link=${HOME}/${name}
    _backup ${link}
    echo "  link [${link}] -> [${real}]"
    ln -s ${real} ${link}
}

_link ${PWD}/bash/.profile
_link ${PWD}/bash/.bashrc

