#!/usr/bin/env bash

cd $(dirname $0)

_backup () {
    [ -L ${1} ] && rm ${1}
    [ -e ${1} ] && echo "  move: [${1}] -> [${1}.BACKUP]"
    [ -e ${1} ] && mv ${1} ${1}.BACKUP
}

_link () {
    real=$1
    name=$(basename $1)
    [ ! ${name:0:1} == . ] && name=.${name}
    link=${HOME}/${name}
    _backup ${link}
    echo "  link [${link}] -> [${real}]"
    ln -s ${real} ${link}
}

_link ${PWD}/bash/.profile
_link ${PWD}/bash/.bashrc
